package app;

import javax.swing.table.DefaultTableModel;

public class ListaPersonaIU extends javax.swing.JFrame {
    
    // Atributos
    private RegistroPersona registroPersona;
    private DefaultTableModel modeloTabla; // la fuente de datos que se muestran en la tabla
    
    public ListaPersonaIU() {
        initComponents();
    }
    
    public ListaPersonaIU(RegistroPersona registroPersona){
        initComponents();
        this.registroPersona = registroPersona;
        // Conectar el modelo de la tabla con la Tabla Lista Alumnos
        // Crear el modelo tabla
        modeloTabla = new DefaultTableModel();
        this.tablaListaAlumnos.setModel(modeloTabla);
        // Crear las columnas de la Tabla
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("DNI");
        modeloTabla.addColumn("Nombres");
        modeloTabla.addColumn("Prioridad");
        modeloTabla.addColumn("Edad");
        modeloTabla.addColumn("Carrera");
        modeloTabla.addColumn("Asunto");
        modeloTabla.addColumn("Documento de Referencia");
        // Registrar la lista de alumnos en el modeloTabla
        moverArregloAModeloTabla();        
    }
    
    private void moverArregloAModeloTabla(){
        // Recuperar la lista de Alumno
        for (int i = 1; i <= registroPersona.longitud(); i++) {
            String[] fila = new String[8];
            fila[0]= String.valueOf(registroPersona.iesimo(i).getID());
            fila[1] = String.valueOf(registroPersona.iesimo(i).getDni());
            fila[2] = registroPersona.iesimo(i).getNombres();
            fila[3]= String.valueOf(registroPersona.iesimo(i).getPrioridad());
            fila[4]= String.valueOf(registroPersona.iesimo(i).getEdad());
            fila[5]= String.valueOf(registroPersona.iesimo(i).getCarrera());
            fila[6]= registroPersona.iesimo(i).getAsunto();
            fila[7]= String.valueOf(registroPersona.iesimo(i).getDocumento());
            // Agregar esta fila al modelo Tabla
            modeloTabla.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaAlumnos = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Personas");

        jLabel1.setText("Lista de Alumnos registrados en el Sistema");

        tablaListaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaListaAlumnos);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jButton1.setText("Eliminar Alumno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(jButton1))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dniStr = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el DNI de la persona a eliminar:");
        if (dniStr != null && !dniStr.trim().isEmpty()) {
            try {
                int dni = Integer.parseInt(dniStr);
                    if (registroPersona.eliminar(dni)) {
                // Eliminar la fila del modelo de la tabla
                for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                    if (Integer.parseInt((String) modeloTabla.getValueAt(i, 1)) == dni) {
                        modeloTabla.removeRow(i);
                        break;
                    }
                }
                javax.swing.JOptionPane.showMessageDialog(this, "Persona eliminada exitosamente.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró una persona con el DNI proporcionado.");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "DNI inválido. Por favor, ingrese un número.");
        }
    }
    // Pedir el DNI a eliminar
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPersonaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPersonaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPersonaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPersonaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPersonaIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaListaAlumnos;
    // End of variables declaration//GEN-END:variables
}
